In [1]:
import numpy as np

예제1 원소가 모두 3인(3, 4, 5)형태의 numpy.array를 출력하시오

In [5]:
arr = np.full([3, 4, 5], 3)
print(arr)

[[[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]]


에제2 정수 -50~50의 범위 안의 난수로 이루어진 (4,5)형태의 numpy.array를 출력하고 행을 기준으로 오름차순 정렬한 전체 배열을 1차원 배열로 변경하여 오름차순 정렬한 결과를 출력하시오.

In [9]:
arr = np.random.randint(-50, 50, (4,5))
print(np.sort(arr, axis=1))
print(np.sort(arr, axis=None))

[[-46 -13  11  33  47]
 [-19 -15  -2   7  22]
 [-31  -8  11  22  35]
 [-43 -35 -27  12  28]]
[-46 -43 -35 -31 -27 -19 -15 -13  -8  -2   7  11  11  12  22  22  28  33
  35  47]


In [10]:
py_list = [
    np.full(3, 8),
    np.array([33, -15, 26]),
    np.linspace(17, 26, 3)
]
print(py_list)

[array([8, 8, 8]), array([ 33, -15,  26]), array([17. , 21.5, 26. ])]


예제3 다음과 같은 파이썬 list가 존재한다. list안에 있는 각 numpy.array의 원소들의 평균값과 표준편차, 중앙값을 순서대로 구하여 구한 순서대로 원소가 이루어진 새로운list를 구성하고 출력하시오.
 예시 : 각 배열의 평균값이 3.0,4.0,5.0이고 표준편차가 1.5,1.7,1.9이며 중앙값이 1.0,2.0,3.0이라면 배열로 구성하여 [3.0,4.0,5.0,1.5,1.7,1.9,1.0,2.0,3.0]으로 출력한다.

In [13]:
result = []
for i in py_list:
    result.append(np.mean(i))
    result.append(np.std(i))
    result.append(np.median(i))
print(result)

[8.0, 0.0, 8.0, 14.666666666666666, 21.171259344267224, 26.0, 21.5, 3.6742346141747673, 21.5]


In [15]:
arr = np.arange(2, 20, 2).reshape((3, 3))

In [16]:
print(arr)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


예제4 다음과 같은 np.array가 존재한다. 이 배열을 행을 기준으로 3개의 배열로 분할하여 분할된 각 배열의 원소들을 제곱한 결과를 다시 원본 배열에 행을 기준으로 병합하시오.

In [22]:
arr_vsplit = np.vsplit(arr,3)
print(arr_vsplit)
s2 = np.square(arr_vsplit)
print(s2)
s3 = np.squeeze(s2,axis = 1)
print(s3)
result = np.vstack((arr, s3))
print(result)

[array([[2, 4, 6]]), array([[ 8, 10, 12]]), array([[14, 16, 18]])]
[[[  4  16  36]]

 [[ 64 100 144]]

 [[196 256 324]]]
[[  4  16  36]
 [ 64 100 144]
 [196 256 324]]
[[  2   4   6]
 [  8  10  12]
 [ 14  16  18]
 [  4  16  36]
 [ 64 100 144]
 [196 256 324]]
