In [3]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3])

In [5]:
print(arr)

[1 2 3]


In [6]:
arr_2 = np.array([[1, 2, 3],
                   [4, 5, 6]])

In [8]:
print(arr_2)

[[1 2 3]
 [4 5 6]]


In [10]:
tuple = (1, 2, 3)
arr = np.array(tuple)
print(arr)

[1 2 3]


In [43]:
lists = [1, 2, 3]
arr = np.array(lists)
print(arr)

[1 2 3]


In [14]:
arr = np.array([1, 2, 3])
print(arr.shape)

(3,)


In [18]:
arr = np.array([[1, 2, 3],
               [4, 5, 6]])
print(arr.shape, arr.ndim, arr.size)

(2, 3) 2 6


In [23]:
arr = np.zeros([2, 2])
print(arr)

[[0. 0.]
 [0. 0.]]


In [26]:
arr = np.full([3,3], 5)
print(arr)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [35]:
arr = np.zeros([2,2,3])
print(arr)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [46]:
arr = np.arange(9)
print(arr)

arr1 = np.arange(3, 9)
print(arr1)

[0 1 2 3 4 5 6 7 8]
[3 4 5 6 7 8]


In [51]:
arr = np.arange(9)
print(arr)
print(arr[0])

[0 1 2 3 4 5 6 7 8]
0


In [53]:
arr = np.array([5, 10, 15, 20, 25, 30])
print(arr[[0, 2, 4]])

[ 5 15 25]


In [59]:
arr = np.array([[5, 10, 15, 20],
              [25, 30, 35, 40],
              [45, 50, 55, 60]])
print(arr[[2], 0:2])

[[45 50]]


In [60]:
arr1 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr2 = np.array([[2, 2, 2],
                [2, 2, 2],
                [2, 2, 2]])

In [61]:
print(arr1 + arr2)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [69]:
for i in range(3):
    arr3 = np.full([3, 3],(i+3))
    print(arr3 + arr1)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [70]:
print(np.add(arr1,arr2))

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [71]:
print(arr1 * arr2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [82]:
arr1 = np.array([2, 3, 4])
arr2 = np.array([1, 2, 3])

print(np.dot(arr1,arr2))

20


In [83]:
arr1 = np.array([[1, 2],
                 [4, 5]])
arr2 = np.array([[1, 2],
                 [0, 3]])

print(np.dot(arr1,arr2))

[[ 1  8]
 [ 4 23]]


In [86]:
arr = np.array([[1, 2, 3],
                [3, 1, 4]])
print(np.sum(arr))

14


In [87]:
arr1 = np.array([[0, 0, 0],
                 [1, 1, 1],
                 [2, 2, 2]])
arr2 = np.array([5, 6, 7])

print(arr1 + arr2)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [89]:
arr1 = np.array([1, 1, 1])
arr2 = np.array([[3], 
                 [4], 
                 [5]])
print(arr1 + arr2)

[[4 4 4]
 [5 5 5]
 [6 6 6]]


In [90]:
arr = np.random.randint(10, size=10)
print(arr)

[3 7 9 1 3 5 6 2 6 0]


In [93]:
arr = np.array([[1, 2, 9],
                [3, 4, 10],
                [6, 7, 11]])
print(arr.T)

[[ 1  3  6]
 [ 2  4  7]
 [ 9 10 11]]


In [97]:
arr = range(1, 9)
print(arr)

range(1, 9)


In [99]:
arr = np.arange(1, 9)
arr = np.insert(arr, 2, 50)
print(arr)

[ 1  2 50  3  4  5  6  7  8]
